### ISSUE TITLE
Image extensions

### ISSUE THREAD

**Issue by binchik** [jaydenseric/apollo-upload-server#1]
Hello! Thanks for your work! I'm trying to use apollo-upload-server to upload images.

The question is how do I add extensions to uploaded files' filenames?

**Comment by jaydenseric** [comment]
Long story short, you have two options to permanently store the file with an extension when storing the temp uploaded file:

- Use the original file name string passed in to the resolver. Be aware that the uploaded extension might not best match the MIME type (accidentally or maliciously) or may be inconsistent (JPEG/jpeg/JPG/jpg).
- Use a package to try to set the best file extension by inspecting the file.

Long story, for images, you probably don't want to. Here is how I suggest doing it...

In the resolver validate the file by looking at the file details passed in or even inspect the uploaded temp file directly, depending what you are looking for.

Once you are happy with the uploaded file, immediately move it to wherever you want to permanently store it. This way you can quarantine uploads from storage. Then on demand generate and cache thumbnails. So:

 - `uploads/temp`
 - `uploads/store`
 - `uploads/cache`

In my setup, I create a MongoDB record with the file data and use the ObjectID (`.toHexString()`) to name the stored file. Users never access the uploaded file directly, but via thumbnailing with [sharp](https://github.com/lovell/sharp).

Here is what my file/image related types look like:

```graphql
input Upload {
  name: String!,
  type: String!,
  size: Int!,
  path: String!
}

type File {
  name: String!,
  type: String!,
  size: Int!
}

type Thumbnail {
  id: String!
  url: String!
  width: Int!
  height: Int!
  format: String!
}

type Image {
  id: String!
  file: File!
  thumbnail (width: Int, height: Int, format: String): Thumbnail!
}
```

I add an image to a type like this:

```graphql
type User {
  id: String!
  email: String!
  avatar: Image
}
```

And query like this:

```graphql
query getUserAvatar ($userId: String!, $avatarSize: Int!) {
  user (userId: $userId) {
    id
    avatar {
      id
      file {
        name
        type
        size
      }
      thumbnail (width: $avatarSize, height: $avatarSize, format: "jpeg") {
        id
        url
      }
    }
  }
}
```

`id` everywhere allows better Apollo client caching. The `file` data gets pulled from the DB, and can be queried without messing with actual files. The magic happens in the `thumbnail` resolver in the `Image` type. The resolver accepts a format from a configured whitelist. The thumbnailer looks up the stored file in the directory by ID, without having to workout what the original uploaded extention was. Very simple. It uses that master file to create the thumbnail as desired.

Here is what it looks like:

<img width="296" alt="screen shot 2017-03-18 at 11 27 17 am" src="https://cloud.githubusercontent.com/assets/1754873/24067232/e7a40944-0bcd-11e7-8f00-b0edb584520b.png">

The temp directory should usually be empty.

I just statically serve the `uploads/cache` directory.

Because thumbnails are created via GraphQL, you can authorise certain users to create thumbs, track who is requesting a lot of thumbs, and potentially throttle/cut them off if they are abusing.

I might publish the thumbnailer to NPM if their is interest. There are not many guides on uploads/thumbnailing in an Apollo project, so if this approach holds up I might write one.

Does this help?

**Comment by binchik** [comment]
Wow! Big thanks for your answers, @jaydenseric. It is definitely helpful. I'll try a close implementation of what you've described here.

**Comment by SPAHI4** [comment]
@jaydenseric thanks, it was very helpful for me too! Can you share us a small example of the resolvers code?

**Comment by jaydenseric** [comment]
@SPAHI4 Sure 🙂

Here is a direct copy-paste of my `thumbnail` resolver on `Image`:

```js
import thumbnail from '../helpers/thumbnail'

export default {
  Image: {
    async thumbnail ({id: fileId}, fields, {origin}) {
      const {width, height, format} = fields
      const thumb = await thumbnail({
        fileId,
        width,
        height,
        format,
        origin
      })
      return {
        id: thumb.url,
        ...thumb
      }
    }
  }
}
```

The `origin` being passed into the context (from Koa) is used by the thumbnailer to return an absolute `url` instead of just a relative path.

My intention is to refactor this resolver and thumbnailer so the thumbnailer does not refer to my application config internally for things such as the file store, cache and paths. Also, it should not assume MongoDB. Once it is generic I will publish it to NPM, potentially this weekend.

There was a surprising amount to be figured out in the thumbnailer code; in particular image orientation gotchas. It's about 90 lines, so I will share it properly once it's ready.

**Comment by savovs** [comment]
Here's how I check type in a mutation that uploads the file to Amazon S3 and returns the URL. Using [file-type](https://github.com/sindresorhus/file-type) to determine type after file is uploaded to a temp directory. 
```javascript
import uuid from 'uuid'; // for file upload
import fs from 'fs';
import readChunk from 'read-chunk';
import fileType from 'file-type';

	newUserProfilePicture: {
		async resolve(root, { picture }, context) {
			const user = context.user;

			// Get File Type
			// Only needs first 4100 bytes
			const fileTypeBuffer = await readChunk(picture.path, 0, 4100);
			const type = fileType(fileTypeBuffer);

			if (!type) {
				// check
				throw new Error('Wrong file type.');
			}

			// Read whole file
			const stream = fs.createReadStream(picture.path);
			const newFileName = `${uuid.v4()}.${type.ext}`;
			const amazonS3Url = `https://s3.eu-west-2.amazonaws.com/bucketName/${newFileName}`;

			try {
				// Upload file to Amazon S3
				amazonFileSystem.writeFile(
					newFileName,
					stream,
					{ ContentType: type.mime },
				);

				// Save URL to database
				userModel.newProfilePictureById(user.id, amazonS3Url);
			} catch (e) {
				throw new Error(e);
			}

			return amazonS3Url;
		},
	},
```
