### ISSUE TITLE
Multiple file uploads

### ISSUE THREAD

**Issue by rafaelfesi** [jaydenseric/apollo-upload-server#113]
I have not found any example of uploading multiple files, so I'm opening this issue to see if someone could help.

So, I was able to create single file upload, but when it comes to multiple files upload I've been having problems. I did this little snippet to test it, but **it only receives the first file of array**.

TypeDefs:

```js
const typeDefs = `
  scalar Upload

  type Post {
    id: ID!
    title: String!
    description: String!
    publishing_date: String!
    category: PostCategory!
    files: [String!]!
  }

  createPost(title: String!, description: String!, publishing_date: String!, category_id: ID!, files: [Upload!]!): Post
`
```

Resolver:
```js
async createPost(_, { title, description, publishing_date, category_id, files }) {

  let process_upload = async upload => {
    let { filename, mimetype, encoding, createReadStream } = await upload
    let stream = createReadStream()
    filename = slugify(filename, { lower: true })
    console.log("============ TEST INI ============")
    console.log("stream: "+ stream)
    console.log("filename: "+ filename)
    console.log("mimetype: "+ mimetype)
    console.log("encoding: "+ encoding)
    console.log("========== TEST END ==========")
    return {
      stream,
      filename,
      mimetype,
      encoding
    }
  }

  Promise.all(files.map(process_upload)).then(async function(file_uploaded) {
    const util = require('util')
    console.log("INSPECT 1: " + util.inspect(file_uploaded[0], {showHidden: false, depth: null} ))
    console.log("x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x")
    console.log("INSPECT 2: " + util.inspect(file_uploaded[1], {showHidden: false, depth: null} ))
  })

}
```

**Comment by jaydenseric** [comment]
The problem in that example is that each `stream` is not being promisified, awaiting either the upload error or completion events.

**Comment by rafaelfesi** [comment]
Thanks for the help @jaydenseric. I solved by following the example and understanding what was missing according to what you said.

My `process_upload` function is something like this, now:
```js
let process_upload = async upload => {
  let { filename, mimetype, encoding, createReadStream } = await upload
  let stream = createReadStream()

  filename = slugify(filename, { lower: true })
  let path = '/tmp/'+ filename

  return new Promise((resolve, reject) =>
    stream
      .on('error', error => {
        if (stream.truncated)
          // Delete the truncated file
          fs.unlinkSync(path)
        reject(error)
      })
      // .on('data', (chunk) => {
      //   console.log('received ' + chunk.length + 'bytes of data')
      // })
      .pipe(fs.createWriteStream(path))
      // .on('error', error => reject(error))
      .on('finish', () => resolve({
        path, filename, mimetype, encoding
      }))
  )
}
```

**Comment by jaydenseric** [comment]
Glad you worked it out in the end :)

**Comment by twelve17** [comment]
@jaydenseric Is the implication that, for multiple uploads, we need to write the streams to files before sending them to another destination?  I'm trying to pass on the original streams from each  upload's `createReadStream()` to a `request` that calls an API, but the result seems to only have partial data of one of the attachments.

**Comment by mike-marcacci** [comment]
Hi @twelve17 you definitely don’t have to write your uploads to the file system. It should be possible to pipe the stream directly to anything that conforms to node’s WritableStream protocol, or by attaching data event listeners.

**Comment by adnanchang** [comment]
hi,,,, i was using this exact same way of uploading files. it was all handy dandy until a day ago i started getting the following error:

`{ BadRequestError: Request disconnected during file upload stream parsing.
[server]     at IncomingMessage.request.once (F:\repos\pushbox\node_modules\graphql-upload\lib\processRequest.js:245:35)
[server]     at Object.onceWrapper (events.js:285:13)
[server]     at IncomingMessage.emit (events.js:197:13)
[server]     at resOnFinish (_http_server.js:583:7)
[server]     at ServerResponse.emit (events.js:202:15)
[server]     at onFinish (_http_outgoing.js:683:10)
[server]     at processTicksAndRejections (internal/process/next_tick.js:74:9)
[server]   message: 'Request disconnected during file upload stream parsing.',
[server]   expose: true,
[server]   statusCode: 499,
[server]   status: 499 }`

and this has been really annoying me. it happens when i upload more than 1 file. turns out that when there are two files, the first file falls to an error and the second file continues to upload. why could this be happening?

**Comment by jaydenseric** [comment]
@adnanchang in you resolvers, you need to make sure that for each file upload, the…

- Awaiting of the file upload
- Stream coming in
- Stream going out to storage

…are all handled asynchronously, so that if an error happens at any of those stages for one upload, it won't poison the success of the others.

What happens if the uploads are working fine, but the service you are forwarding the files to has a temporary network error for one of the files going out? Would that crash the processing of all of the uploads, cause the resolver to reject, resulting in an early response back to the client while it is still trying to upload the remaining files?

Generally `Promise.all` is not a good fit for this as a single error will cause it to reject. There are packages available that do a similar thing except once it resolves it has the success or failure results for each promise that was provided.

**Comment by adnanchang** [comment]
@jaydenseric, thank you for the reply, turns out, i was just looking at the wrong places. as you suggested, they need to be handled asynchronously that means there has to be an await. 

turns out, all i was missing was an `await` keyword before opening my `Promise.all` function. i never had an idea that `Promise.all` would need an await. that's why it was crashing since it would start processing the new file before the first file would finish the stream and thus crashing. 

if you're interested, you might wanna look [here](https://stackoverflow.com/questions/55216860/graphql-error-when-resolving-promises-during-file-upload)

**Comment by hbw3** [comment]
Awesome
