### ISSUE TITLE
formidable vs muddler

### ISSUE THREAD

**Issue by du5rte** [jaydenseric/apollo-upload-server#12]
Hey, great package I got it working pretty quick!

One use case I think was missed is stream files directly to [S3 Buckets](https://aws.amazon.com/s3/) without ever writing to the disk. 

I've noticed it uses  `formidable` which saves it to the **disk** without an option to hold it in **memory** but on the [@danielbuechele](https://github.com/danielbuechele)’s [Medium article](https://medium.com/@danielbuechele/file-uploads-with-graphql-and-apollo-5502bbf3941e) he uses [multer](https://github.com/expressjs/multer#api) which has options for saving to the `DiskStorage` or `MemoryStorage`, was there a reason to choose `formidable` over `multer` as I see a big lost in flexibility?

**Comment by jaydenseric** [comment]
I tried out about 4 options in the early days of this project. It's been a while since I made the choice, but there are a couple of reasons. Firstly, memory storage is not really desirable because you can easily use up all the available memory on the server. Then it really comes down to a choice of quality, ease-of-use and popularity/support:

- For quality, I found comparative benchmarks (can't find them again now) that suggested formidable had great performance.
- All the major options are suffering maintenance backlog, but formidable has a much more elegant codebase (zero dependencies) than multer (8 dependencies, including busboy). I tried using busyboy on it's own, but that got overly complicated.
- For ease of use, formidable was by far the simplest and cleanest to use for our purposes.
- Regarding popularity, formidable is dominant with 243k daily installs vs 75k for multer.

I have been pretty happy with the choice so far.

I am working with the Apollo team to look at bringing upload functionality into the official GraphQL servers, so there is an opportunity to improve a few things. For a while I have wanted to pass file streams into resolvers, but in experimentation it was challenging to engineer. If it turns out to be possible, developers could do whatever they want with uploads in the resolver and it could be an amazing performance boon for passing files through to cloud storage.

Keep in mind that uploads need to be inspectable for validation purposes in the resolver before permanent cloud storage happens, ruling out a configurable cloud upload process in `apollo-upload-server`. My vision is for there to be no Apollo client and GraphQL server uploads config, it just works; developers can decide what to do with uploads in the resolver.

Feel free to discuss further, we can reopen if something actionable comes up.

**Comment by du5rte** [comment]
Thanks for getting back to me @jaydenseric, passing streams to resolvers sounds promising and solves both issues. What challenges did you have trying to pass streams to resolver?

It's gonna be awesome once this library become part of apollo 🤙

**Comment by du5rte** [comment]
> By the time you have parsed the full list of files to pass into the resolvers, the upload has virtually finished anyway

I've tried couple approaches first with `koa-multer` to work with the `memoryStorage`. I'm only dealing with avatar pictures but you're probably right bigger files can start to take a lot of memory. I guess this is what you mean by blocking the graphlQL server and resolvers the middleware is holding while it parses and read files before progressing and by the time it reaches the resolver it has already handle the upload.

```js
import multer from "koa-multer";

app.use(multer({
    storage: multer.memoryStorage(),
}).any())
```

```js
export function processRequest(request, options) {
  // Parse the multipart form request

  const { body, files } = request

  // Decode the GraphQL operation(s). This is an array if batching is
  // enabled.
  const operations = JSON.parse(body.operations)

  // Check if files were uploaded
  if (files.length) {
    // File field names contain the original path to the File object in the
    // GraphQL operation input variables. Relevent data for each uploaded
    // file now gets placed back in the variables.
    const operationsPath = objectPath(operations)

    files.forEach((file) => {
      const {
        originalname: name,
        mimetype: type,
        size,
        fieldname,
        buffer
      } = file

      operationsPath.set(fieldname, { name, type, size, buffer })
    })
  }

  return operations;
}
```
![capture](https://user-images.githubusercontent.com/7394762/29675981-b633cad6-88ee-11e7-8582-7b771c862908.PNG)

Second approached with `busboy`, my knowledge of streams is not great so I'm not sure how performant this is but it works, also not the prettiest code. It does the minimal work on the multipart form to structure the variables and skips reading the stream letting the resolver do it if they which to, a downside is you don't know how big the file is, but maybe that can be uploaded from the front end?

```js
export async function busboyPromise(ctx) {
  return new Promise(function(resolve, reject) {
    const results = {
      fields: [],
      files: []
    }

    const busboy = new Busboy({ headers: ctx.req.headers });

    busboy.on('file', function(fieldname, stream, filename, encoding, mimetype) {
      // ReadStream
      results.files.push({
        filename,
        mimetype,
        encoding,
        fieldname,
        stream
      })

      stream.resume();
      // file.on('data', function(data) {
      //   // buffer
      // });
      // file.on('end', function() {
      // });
    });
    busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated, encoding, mimetype) {
      results.fields[fieldname] = val
    });
    busboy.on('finish', function() {
      resolve(results)
    });

    ctx.req.pipe(busboy);
  });
}


export async function processRequest(ctx, options) {
  // Parse the multipart form request
  const { fields, files } = await busboyPromise(ctx)

  // Place on request for futher info
  ctx.req.files = files

  // Decode the GraphQL operation(s). This is an array if batching is
  // enabled.
  const operations = JSON.parse(fields.operations)

  // Check if files were uploaded
  if (files.length) {
    // File field names contain the original path to the File object in the
    // GraphQL operation input variables. Relevent data for each uploaded
    // file now gets placed back in the variables.
    const operationsPath = objectPath(operations)

    files.forEach((file) => {
      const {
        filename: name,
        mimetype: type,
        // you don't get size until you read the stream
        // but it could be transfered from the client mutation
        // size,
        fieldname,
        stream
      } = file

      operationsPath.set(fieldname, { name, type, stream })
    })
  }

  return operations
}
```

```js
export default {
  type: new GraphQLNonNull(GraphQLString),
  args: {
    avatar: { type: UploadInput }
  },
  resolve(root, { avatar }, ctx, info) {
    console.log(avatar)

    avatar.stream.pipe(fs.createWriteStream(path.resolve(__dirname, avatar.name)))

    return `New avatar saved`;
  }
};
```

![capture2](https://user-images.githubusercontent.com/7394762/29680124-92ec5ec8-88fb-11e7-97d9-9f09d4b3d294.PNG)
