### ISSUE TITLE
Cannot name file

### ISSUE THREAD

**Issue by maka-io** [jaydenseric/apollo-upload-server#14]
I don't see a way to name the files as they are uploaded, they just get a name of "upload_<some uuid>" is there a way to change that, or append an extension?

**Comment by jaydenseric** [comment]
The original files are available, you can rename the uploads to whatever you like when moving them to permanent storage.

**Comment by maka-io** [comment]
Ok, so that's something I'd have to do manually?  There isn't a setting?

**Comment by jaydenseric** [comment]
Yes, it is something you need to do manually.

You might find [this earlier discussion](https://github.com/jaydenseric/apollo-upload-server/issues/1) interesting, although these days I do things a bit diffirently and permanently store files in MongoDB GridFS.

In the next several weeks, once our platform launches and I get back from a trip to San Fransisco for GraphQL Summit, I hope to work on providing file streams instead of metadata to resolvers ((#13)[https://github.com/jaydenseric/apollo-upload-server/issues/13]).

Hope that helps 🙂

**Comment by maka-io** [comment]
That does, and thank you!

**Comment by savovs** [comment]
Yeah, you'd have to rename it after upload manually. I ended up not storing stuff in my database, just using Amazon S3 with [s3fs](https://github.com/RiptideElements/s3fs):

```javascript
async function uploadToAmazon(path, name = uuid.v4()) {
	try {
		// Get File Type
		// Only needs first 4100 bytes
		const fileTypeBuffer = await readChunk(path, 0, 4100);
		const type = fileType(fileTypeBuffer);

		if (!type) {
			throw new Error('No file type.');
		}

		// RegExp only allow image mime type
		if (!/^image/.test(type.mime)) {
			throw new Error('Wrong file type.');
		}

		// Generate thumbnails and compress

		const newFileName = `${name}.${type.ext}`;
		const stream = fs.createReadStream(path);

		// Upload file to Amazon S3
		amazonFileSystem.writeFile(
			newFileName,
			stream,
			{ ContentType: type.mime },
		);

		return `https://s3.${config.amazonS3.region}.amazonaws.com/yupty/${newFileName}`;
	} catch (e) {
		throw new Error(e);
	}
}

```
