### ISSUE TITLE
Auto delete file from directory?

### ISSUE THREAD

**Issue by SPAHI4** [jaydenseric/apollo-upload-server#2]
I think if there was an error thrown later in the resolver (or other middleware), the uploaded files should be deleted (optionally).

**Comment by jaydenseric** [comment]
Can you think of any sorts of errors where you would *not* want them deleted?

**Comment by SPAHI4** [comment]
I have no idea. Anyway, it can be disabled.

**Comment by jaydenseric** [comment]
Do you mean if there is an error within the `apollo-upload-server` middleware, or anywhere in following app middlewares too? The first would be easier and less risky.

I would hesitate to delete the upload once our middleware has done it's job and passed the details into the resolver. Any errors from that point on would be due to the application code and should be caught and handled by the application developer.

**Comment by SPAHI4** [comment]
I mean the second. 
The error may be thrown somewhere between the `apollo-upload-server` and the actual resolver

**Comment by jaydenseric** [comment]
Closing this in favour of https://github.com/jaydenseric/apollo-upload-server/issues/13.
