### ISSUE TITLE
Problem with uploading of identical files

### ISSUE THREAD

**Issue by vitalix89** [jaydenseric/apollo-upload-server#32]
When I am trying to upload 2 identical files with different names in the same request, apollo-upload-server doesn't handle it well. This is probably due strange behavior of busboy. Problematic piece of code:

`/src/index.mjs`
```js
const upload = new Promise(resolve =>
  busboy.on('file', (fieldName, stream, filename, encoding, mimetype) =>
    fieldName === mapFieldName && resolve({ stream, filename, mimetype, encoding })
  )
)
```

This statement (```mapFieldName && resolve```) always returns false when it parses the second file, so the promise never gets resolved. 

Is there any way to solve this issue? 

Thanks for the cool library, loving it!

**Comment by jaydenseric** [comment]
That's really strange, because busboy should not care if the file contents are the same or different. 

In [the PR for the next version](https://github.com/jaydenseric/apollo-upload-server/pull/31), there are tests for mulitple files in one request and the same test file is used multiple times and everything works ok. The use of listeners and things has been totally refactored for the update, so that code example is gone now anyway.

Feel free to test out the PR early, otherwise I hope to release it sometime early this week.

**Comment by jaydenseric** [comment]
`apollo-upload-server` [v4.0.0-alpha.2](https://github.com/jaydenseric/apollo-upload-server/releases/tag/v4.0.0-alpha.2) is out! Please give it a go and see if it resolves your issue 🙏

The `apollo-upload-examples` API has been [updated accordingly](https://github.com/jaydenseric/apollo-upload-examples/commit/ee32d8ced7a26e6b65ea8c8d5537dd54a78b823e), so perhaps take a look at the changes to error handling.

**Comment by vitalix89** [comment]
Thanks, it works fine with v4.0.0-alpha.2
