### ISSUE TITLE
Support for Node 6 (needed for AWS Lambda)

### ISSUE THREAD

**Issue by schickling** [jaydenseric/apollo-upload-server#33]
Would be great if you could adjust the babel compilation settings in a way that the resulting output also runs in Node 6 (or even lower). Otherwise it's not possible to deploy apps using `apollo-upload-server` to AWS Lambda.

**Comment by jaydenseric** [comment]
Thanks for the head's up 🙂

That's really surprising/disappointing to see AWS provides such an outdated Node.js version.

The primary reason for the Node.js v7.6 requirement here is that it is the earliest version to support native async/await. A lot of big projects, [such as Koa](https://github.com/koajs/koa#installation), support down to this v7.6 for this reason.

Surely people must be screaming at AWS Lambda for native async/await support. With short time this problem will surely resolve itself; I don't really intend take this project back to `.then()` chains or more complex transpilation.

AWS Lambda users can transpile `apollo-upload-server` to get it working in the meantime.

**Comment by schickling** [comment]
I think you misunderstood me here: I'm not saying you should rewrite this project using `.then()` but rather transpile it by default so other people don't have to. This is a general best practice for node libraries and already caused quite a lot of frustration for packages not following this pattern (like `apollo-upload-server`). Hope you can take a stab at this 👍

**Comment by jaydenseric** [comment]
I know *how* to do it; we used to support Node.js v6.4. I and a lot of other package authors consciously chose to drop support for v6 since it is a year and a half old now; v7.6 with native async/await has been out for almost a year and v8.x LTS is out now.

The min required Node.js version has always been visible and accurate in package.json `engines` so there should not have been nasty surprises. As for best practices, AWS should really provide reasonably recent versions of Node.js, especially if users are becoming increasingly frustrated that newer packages are not compatible with the legacy environment.

It's a shame for the majority to lose native async/await, but until AWS Lambda provides more up-to-date versions of Node.js I can trial dropping support back down to Node.js v6.10+. I want everyone to have a great experience using `apollo-upload-server` 🙏

**Comment by jaydenseric** [comment]
Just published `apollo-upload-server` [v4.0.0-alpha.2](https://github.com/jaydenseric/apollo-upload-server/releases/tag/v4.0.0-alpha.2) 🚀

**Comment by schickling** [comment]
Great job @jaydenseric !
