### ISSUE TITLE
Getting an empty object {} in server instead of file

### ISSUE THREAD

**Issue by saostad** [jaydenseric/apollo-upload-server#73]
Hi, 
I am getting an empty object in server!
can you please tell me what is my problem?

**server.js:** 
```
app.use(
  "/graphql",
  bodyParser.json(),
  apolloUploadExpress(/* Options */),
  graphqlExpress((req: any) => {
    return {
      schema,
      context: {
        EMP_ID: req.EMP_ID
      }
    };
  })
);
```

**Type Definition:** 
```
scalar Upload
type File {
  id: ID!
  path: String!
  filename: String!
  mimetype: String!
  encoding: String!
}
```

**Mutations:** 
`uploadFile (file: Upload!): File!`

**resolvers object:**
```
import { GraphQLUpload } from "apollo-upload-server";
const resolvers = {
  Upload: GraphQLUpload,
  Query: queryResolvers,
  Mutation: mutationsResolvers
};
```

**Resolver:** 
`uploadFile: (_: any, { file }) => saveFile.processUpload(file)`

**saveFile Module:** 
```
import * as fs from "fs";
import { logger } from "./index";

const uploadDir = "./uploads";

const storeFS = ({ stream, filename }) => {
  const id = Date.now();
  const path = `${uploadDir}/${id}-${filename}`;
  return new Promise((resolve, reject) =>
    stream
      .on("error", error => {
        if (stream.truncated)
          // Delete the truncated file
          fs.unlinkSync(path);
        reject(error);
      })
      .pipe(fs.createWriteStream(path))
      .on("error", error => reject(error))
      .on("finish", () => resolve({ id, path }))
  );
};

const processUpload = async upload => {
  try {
    console.log(upload);
    const { stream, filename, mimetype, encoding } = await upload;
    console.log(stream, filename, mimetype, encoding);
    return await storeFS({ stream, filename });
  } catch (error) {
    logger.log(error);
  }
};

export const saveFile = {
  processUpload
};
```

**In Client in React Component:**
```
import React from "react";

import { graphql } from "react-apollo";
import gql from "graphql-tag";

const UploadFile = ({ mutate }) => {
  const handleChange = ({
    target: {
      validity,
      files: [file]
    }
  }) => {
    validity.valid &&
      mutate({
        variables: { file }
      });
  };

  return <input type="file" required onChange={handleChange} />;
};

export default graphql(gql`
  mutation($file: Upload!) {
    uploadFile(file: $file) {
      id
      filename
      encoding
      mimetype
      path
    }
  }
`)(UploadFile);
```

**Comment by saostad** [comment]
Problem Solved!

I ddin't config Client Correctly : 
```
import { createUploadLink } from 'apollo-upload-client'

const link = createUploadLink(/* Options */)
```

**Comment by saostad** [comment]
thank you,
for awesome job! 👍

**Comment by jaydenseric** [comment]
Glad you worked it out :)

**Comment by djGrill** [comment]
@saostad Hi,

I'm having the same issue. Please what was exactly wrong with your client config that you fixed afterwards?

Thanks :)

**Comment by djGrill** [comment]
@saostad got it, this was the issue:

https://github.com/jaydenseric/apollo-upload-client/issues/89#issuecomment-384923295

**Comment by SanchiSinghal** [comment]
@djGrill @saostad   Hey, 
I still can't resolve the issue .
I'm using both httplink and uploadlink iwth react and typescript. 
And have used uploadlink instead of httplink still the file object goes {} blank iin network mutation.
Have also, tried the split method in below manner 

const httpLink = new HttpLink({
  credentials: 'include',
  uri: process.env.REACT_APP_SERVER_GRAPH_URL
})

const uploadLink = createUploadLink({ uri: 'http://localhost:8080/graphql' })

const requestLink = split(
  operation => operation.getContext().hasUpload,
  uploadLink,
  httpLink
)

const client = new ApolloClient({
  cache: cacheData,
  link: from([cleanTypenameLink, restLink, stateLink, requestLink])
})

Please can you help me with it.

**Comment by jaydenseric** [comment]
@SanchiSinghal 

> I'm using both httplink and uploadlink

Don't do that. Also, make sure you are not using or importing anything from Apollo Boost.

**Comment by SanchiSinghal** [comment]
Yea, even if I remove httplink and just use uploadlink still it doesn't send abything. 
Also, gives following error on console. 
Error: GraphQL error: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

**Comment by jaydenseric** [comment]
@SanchiSinghal if your issue is not the same as this issue; you should either keep investigating or raise a new issue explaining specific steps to reproduce a `graphql-upload` bug. It's not good etiquette to take over old issues and send notifications to everyone in the hope they will provide you support or do investigative work for you. At the very least, please quote errors and format code blocks (without superfluous code/types pasted in with it) properly in markdown like this:

> Error: GraphQL error: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

```js
<input type="file" onChange={e => this.setState({ fileName: e.target.files[0] })} />
```

As always, the first thing to do is make sure you are using the last versions of the client and `graphql-upload` packages. If there is still a problem, the next thing to investigate is if the problem is on the client or server. If you use the network activity inspector to verify the client is sending a valid [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec), you know not to bother looking at the client and focus on the server.

**Comment by jamestrenda** [comment]
Thanks for making this! I got this working once I realized I needed to setup Apollo Client manually vs using Apollo Boost like I was initially. 

However, I need help understanding how to serve the files on my front end with Next.js because when I try to access the backend upload directory directly the file won't load because Next.js wants static files to exist in the /public directory. 

I know this isn't an issue with your code, but would you be able to point me in the direction of how I might accomplish this?  Thanks!

**Comment by jaydenseric** [comment]
@jamestrenda as a general rule, app and API servers/deployments should be considered disposable - don't store any user content on them.

In your resolvers, stream the uploads into cloud storage such as AWS S3 or something similar like [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces).

Then you can use a image thumbnailing CDN provider like [imgix](https://www.imgix.com) that reads from the stored images to and makes them available via URLs with query strings to control dimensions, format etc. for use in your app.

This will allow you to have cheap, scalable and amazingly optimized assets.

**Comment by zhzhang** [comment]
FYI, I was having a similar issue where the file sent to the server was an empty object `{}`.
The issue turned out to be that when using `createUploadLink` and `setContext` for auth together you have to use `createUploadLink().concat(authLink)` in that order. Doing it the wrong way around doesn't error and the requests still get sent to the server, but with `{}` in place of the file.

**Comment by rasmus-rudling** [comment]
> Problem Solved!
> 
> I ddin't config Client Correctly :
> 
> ```
> import { createUploadLink } from 'apollo-upload-client'
> 
> const link = createUploadLink(/* Options */)
> ```

This was my problem too, thanks for posting that!
