### ISSUE TITLE
How to implement this in Apollo Server 2

### ISSUE THREAD

**Issue by arvi** [jaydenseric/apollo-upload-server#87]
Hello,

I'm just wondering given the new syntax of Apollo Server 2:

```
const server = new ApolloServer({ typeDefs, resolvers });
server.applyMiddleware({ app });
```

how would one apply this middleware?

**Comment by jaydenseric** [comment]
You don't need to, it's built in 🎉

You can see the docs here: https://www.apollographql.com/docs/apollo-server/v2/features/file-uploads.html

**Comment by harm-less** [comment]
Mm, ok. I do seem to be able to find anything about this in the documentation from this plugin. So to be clear, since Apollo 2.0, this plugin is no longer necessary or is it loaded automatically? Can you elaborate on this?

**Comment by jaydenseric** [comment]
This project is not a plugin. It is Express and Koa middleware, along with a GraphQL scalar, to add upload support to most GraphQL servers (I've used it with 3 different kinds).

`apollo-server` v2 uses this package built in, so yes, it is "loaded automatically". You will need to handle uploads appropriately in your resolvers of course. Keep in mind that `apollo-server` uses a version of this project that is several versions out of date, and has since-fixed vulnerabilities.
