### ISSUE TITLE
Apollo 2.0 Server Integration

### ISSUE THREAD

**Issue by Victordmdb** [jaydenseric/apollo-upload-server#93]
Is there a way to integrate this with the new structure of Apollo Server 2.0?

**Comment by jaydenseric** [comment]
`apollo-upload-server` is built in to Apollo Server v2, so no setup is required! Here is the official guide: https://www.apollographql.com/docs/guides/file-uploads.html

**Comment by Victordmdb** [comment]
Ah yes, thats great!

A followup question on this, when i try to upload something I get the following error on the server: 

`FileStreamDisconnectUploadError: Request disconnected during file upload stream parsing.
    at IncomingMessage.request.on (/mnt/e/Dev/AdaptiveStreamToolBox/server/node_modules/apollo-server-express/node_modules/apollo-upload-server/lib/middleware.js:151:15)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at resOnFinish (_http_server.js:564:7)
    at ServerResponse.emit (events.js:182:13)
    at ServerResponse.EventEmitter.emit (domain.js:442:20)
    at onFinish (_http_outgoing.js:683:10)
    at afterWrite (_stream_writable.js:480:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at IncomingMessage.request.on (/mnt/e/Dev/AdaptiveStreamToolBox/server/node_modules/apollo-server-express/node_modules/apollo-upload-server/lib/middleware.js:149:32)
    at IncomingMessage.emit (events.js:182:13)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Comment by jaydenseric** [comment]
`FileStreamDisconnectUploadError` means that either the client aborted while the file upload stream was being parsed (can happen if an impatient user presses browser refresh) or if the server sends a response back to the client before the file upload stream has finished.

In your case, it is most likely that your resolver is not awaiting the file upload stream to finish before returning/resolving. When all GraphQL resolvers have resolved the GraphQL server middleware sends a response.

Note that in `apollo-upload-server` v5, there were nasty bugs where some errors could not be caught properly in resolvers and it would end up crashing the server. [v6 fixes these bugs](https://github.com/jaydenseric/apollo-upload-server/blob/master/changelog.md#600-alpha1), so chances are if you could upgrade such errors would be easier to handle.

Unfortunately, if you use `apollo-server`, you might not be able use the updated `apollo-upload-server` for some time because it's an internal dependency. Apollo intend to support Node.js v6, but the new version of `apollo-upload-server` supports Node.js v8.5+. For this reason, it might be a long time before Apollo updates. It's a dilemma 😓

**Comment by Victordmdb** [comment]
Hmm I believe the issue is coming from the client side, since when i try a dummy upload with graphiql `file : "text.png"` it will be processed, but using an input box with an actual file fails.

**Comment by jaydenseric** [comment]
The client will only send a multipart request if the query/mutation contains actual `File` (or a few other file-like type) instances.

**Comment by jaydenseric** [comment]
Here is an example of awaiting an upload stream to complete: https://github.com/jaydenseric/apollo-upload-examples/blob/master/api/resolvers.mjs#L21

**Comment by Victordmdb** [comment]
Hmm the error I have is indeed the client and I believe it has to do with combining uploadlink with persisted query.

Before using the uploadlink, when defining ApolloClient, I had a apollo-link split to separate a websocket link (for subscriptions) and a link which combined an httplink, auth and persisted query middlewares.

If I just replace the httpLink with the uploadLink, this is when it fails.

If I remove one of the persisted query mw, it will start working again.

Would it make sense that i separate uploadlink from the persisted query? Or should it theoretically work as is.

**Comment by jaydenseric** [comment]
I don't have quick answers for you as I don't use persisted queries, sorry.

People have investigated usage with persisted queries before (see https://github.com/jaydenseric/apollo-upload-client/issues/75) but I'm not sure conclusions were shared.

There are `#apollo-client`, `#apollo-link` and `#uploads` channels in the Apollo Slack team for asking general questions or picking brains; I get notifications when the keyword "upload" is used.

We can pick this up in a new `apollo-upload-client` issue if it turns out to be a bug.

**Comment by Victordmdb** [comment]
Alright, thanks for the quick feedback! I'll have to pass on persisted queries until i have more time to investigate.

**Comment by d3vhound** [comment]
@Victordmdb did you ever figure this out? Currently running into the same conclusions but with one caveat. The file upload works if the query is saved in the cache db but if it isn't then apollo client continues the request without the file variables. Everything works without the persisted queries link.
