### ISSUE TITLE
Getting empty object instead of file

### ISSUE THREAD

**Issue by jordan-jarolim** [jaydenseric/apollo-upload-server#94]
Hi, I ran into this problem and cannot figure it out. Once I upload file using apollo-upload-client + apollo-upload-server I am getting an empty object {} instead of a file. I went through several issues and everything seems to be set up correctly. 
1) I have set createUploadLink (https://github.com/jaydenseric/apollo-upload-server/issues/73)
2) My payload looks like this - https://github.com/jaydenseric/graphql-multipart-request-spec#request-payload (https://github.com/jaydenseric/apollo-upload-client/issues/82)
3) I have followed all the other steps in readme such as `scalar Upload` etc...

Here is my server config:

`server.use('/graphql', bodyParser.json(), auth, apolloUploadExpress(), graphqlExpress((req, res) => {
 const context = {
 user: req.user,
 req,
 res,
};
return {
schema,
context,
};
}));
`
Is there any known issue with bodyParser as mentioned in one of referenced issues? Could you point me to any other direction please?

Thanks

**Comment by jaydenseric** [comment]
I don't think you need the body parser at all, `apollo-upload-server` does not need it and `express-graphql` can handle that internally.

**Comment by jaydenseric** [comment]
Oh, sorry I was confused. I think the readme example assumed Apollo, not `express-graphql`. The examples still may need to be updated though: https://www.apollographql.com/docs/apollo-server/essentials/server.html#middleware

**Comment by jordan-jarolim** [comment]
Sorry, this was totally my mistake. I missed that part saying: " the resolver recieves a **promise**...". So I was missing `await` in my resolver. Feel free to close this. Anyway, I have one more question. You are saving the stream data into a file using `pipe` in your example. Is it possible to save data into a variable? I tried to use `on('data', function...)` but the stream seems to be writable only. My use case is that once I get the file I wanna send it over REST to an external service. So creating a file on the disk is not necessary for me. I know this is not related to this issue nor the library but if you know the way, it might help the others as I didnt find any solution.

Thanks :)

**Comment by jaydenseric** [comment]
Glad you worked it out! As for passing the file on to an external service using REST, you should be able to pipe the stream to a multipart form field when using libraries such as [`form-data`](https://www.npmjs.com/package/form-data) and [`node-fetch`](https://www.npmjs.com/package/node-fetch).

**Comment by mike-marcacci** [comment]
@jordan-jarolim the stream should be a duplex stream, (it’s actually a writable stream that proxies readable methods/events to a readable stream) so the data event should work... if it doesn’t, it will once #92 lands, since it bumps the version of capacitor to one that uses a real read stream as opposed to a proxy.

**Comment by jordan-jarolim** [comment]
@mike-marcacci Well I tried the example using pipe with file output but it behaves little bit nondeterministic. It sometimes produces an empty file of 0B (just simple .txt of 2B originally). I also tried own implementation using 'data' or 'readable' events  and I had still the same problem. If I dump a type of the stream using `(streamobj instanceof stream.Readable)` it always gives me false, but gives true for `stream.Writable`. I guess this might be a correct behavior?

**Comment by mike-marcacci** [comment]
Hey @jordan-jarolim thanks for reporting back! What you're describing sounds like a timing issue that was already fixed in `fs-capacitor`. I just checked, and it looks like I never bumped the dependency version here, assuming a patch would automatically be imported. However, since it was pre-`1.0.0`, all new versions are assumed to be breaking. I just manually bumped the version in #97. We'll get that out ASAP, and would much appreciate if you try again: it should work the way you're using it.

Again, once #92 lands, this your `instanceof` check will succeed, as you'll be interacting with a real Readable stream. I'm going to try to finish that up as soon as I get a chance.
